/**
 * Catálogo de provedores suportados pelo Basck Clouds.
 *
 * Cada entrada descreve como o app deve apresentar a integração,
 * que tipo de autenticação ela usa e quais operações são suportadas.
 *
 * As implementações reais de cada provedor ficam em arquivos próprios
 * e todas expõem a interface CloudProvider, garantindo que o motor do
 * cluster (distribuição, busca, backup) possa tratar todas as contas
 * de forma homogênea.
 */
import type { ProviderDescriptor, ProviderId } from '@shared/types';

const infinite = Number.POSITIVE_INFINITY;

export const PROVIDER_REGISTRY: Record<ProviderId, ProviderDescriptor> = {
  googledrive: {
    id: 'googledrive',
    name: 'Google Drive',
    shortName: 'Drive',
    brandColor: '#1A73E8',
    icon: '🟦',
    authKind: 'oauth2',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    scopes: ['https://www.googleapis.com/auth/drive.file', 'openid', 'email', 'profile'],
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 5 * 1024 * 1024 * 1024 * 1024, // 5 TB
    },
    documentationUrl: 'https://developers.google.com/drive/api/v3/about-sdk',
    category: 'consumer',
  },
  onedrive: {
    id: 'onedrive',
    name: 'Microsoft OneDrive',
    shortName: 'OneDrive',
    brandColor: '#0364B8',
    icon: '🟦',
    authKind: 'oauth2',
    authUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    scopes: ['offline_access', 'Files.ReadWrite', 'User.Read'],
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 250 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://learn.microsoft.com/onedrive/developer/',
    category: 'consumer',
  },
  dropbox: {
    id: 'dropbox',
    name: 'Dropbox',
    shortName: 'Dropbox',
    brandColor: '#0061FF',
    icon: '🟦',
    authKind: 'oauth2',
    authUrl: 'https://www.dropbox.com/oauth2/authorize',
    scopes: ['files.content.write', 'files.content.read', 'files.metadata.write', 'account_info.read'],
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 2 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://www.dropbox.com/developers/documentation',
    category: 'consumer',
  },
  mega: {
    id: 'mega',
    name: 'MEGA',
    shortName: 'MEGA',
    brandColor: '#D90007',
    icon: '🟥',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://mega.nz/developers',
    category: 'consumer',
  },
  box: {
    id: 'box',
    name: 'Box',
    shortName: 'Box',
    brandColor: '#0061D5',
    icon: '🟦',
    authKind: 'oauth2',
    authUrl: 'https://account.box.com/api/oauth2/authorize',
    scopes: ['root_readwrite'],
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 150 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://developer.box.com/',
    category: 'business',
  },
  pcloud: {
    id: 'pcloud',
    name: 'pCloud',
    shortName: 'pCloud',
    brandColor: '#00A0EE',
    icon: '☁️',
    authKind: 'oauth2',
    authUrl: 'https://my.pcloud.com/oauth2/authorize',
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: false,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://docs.pcloud.com/',
    category: 'consumer',
  },
  yandexdisk: {
    id: 'yandexdisk',
    name: 'Yandex Disk',
    shortName: 'Yandex',
    brandColor: '#FFCC00',
    icon: '🟨',
    authKind: 'oauth2',
    authUrl: 'https://oauth.yandex.com/authorize',
    scopes: ['cloud:disk.full'],
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 50 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://yandex.com/dev/disk-api/',
    category: 'consumer',
  },
  icloud: {
    id: 'icloud',
    name: 'iCloud Drive',
    shortName: 'iCloud',
    brandColor: '#A2AAAD',
    icon: '☁️',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: false,
      quota: true,
      resumable: false,
      streaming: false,
      chunking: true,
      maxFileSize: 50 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://support.apple.com/icloud/',
    category: 'consumer',
  },
  mediafire: {
    id: 'mediafire',
    name: 'MediaFire',
    shortName: 'MediaFire',
    brandColor: '#E1242D',
    icon: '🔥',
    authKind: 'oauth2',
    authUrl: 'https://www.mediafire.com/application/oauth/authorize/',
    requiresAppCredentials: true,
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://www.mediafire.com/developers',
    category: 'consumer',
  },
  koofr: {
    id: 'koofr',
    name: 'Koofr',
    shortName: 'Koofr',
    brandColor: '#FF6F00',
    icon: '🟧',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 10 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://koofr.eu/help/',
    category: 'consumer',
  },
  jottacloud: {
    id: 'jottacloud',
    name: 'Jottacloud',
    shortName: 'Jotta',
    brandColor: '#F47521',
    icon: '🟧',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://www.jottacloud.com/privacy/',
    category: 'consumer',
  },
  filen: {
    id: 'filen',
    name: 'Filen',
    shortName: 'Filen',
    brandColor: '#0F0F0F',
    icon: '⚫',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://filen.io/developers',
    category: 'consumer',
  },
  terabox: {
    id: 'terabox',
    name: 'TeraBox',
    shortName: 'TeraBox',
    brandColor: '#0E74FF',
    icon: '🅣',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      // Plano grátis: 1.024 MB por arquivo (restrição real do serviço).
      // Plano premium remove o limite.
      maxFileSize: 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://www.terabox.com/developers',
    category: 'consumer',
  },
  internxt: {
    id: 'internxt',
    name: 'Internxt',
    shortName: 'Internxt',
    brandColor: '#0066FF',
    icon: '🟦',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://developers.internxt.com/',
    category: 'consumer',
  },
  s3: {
    id: 's3',
    name: 'Amazon S3',
    shortName: 'S3',
    brandColor: '#FF9900',
    icon: '🟧',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 5 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://docs.aws.amazon.com/s3/',
    category: 'object',
  },
  wasabi: {
    id: 'wasabi',
    name: 'Wasabi',
    shortName: 'Wasabi',
    brandColor: '#F45F1F',
    icon: '🟧',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 5 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://docs.wasabi.com/',
    category: 'object',
  },
  backblazeb2: {
    id: 'backblazeb2',
    name: 'Backblaze B2',
    shortName: 'B2',
    brandColor: '#E82127',
    icon: '🟥',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 10 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://www.backblaze.com/docs/cloud-storage-apis',
    category: 'object',
  },
  gcs: {
    id: 'gcs',
    name: 'Google Cloud Storage',
    shortName: 'GCS',
    brandColor: '#4285F4',
    icon: '🟦',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 5 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://cloud.google.com/storage/docs/apis',
    category: 'object',
  },
  azureblob: {
    id: 'azureblob',
    name: 'Azure Blob Storage',
    shortName: 'Azure',
    brandColor: '#0072C6',
    icon: '🟦',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 4_769_313_476_710_400, // ~4.75 TB
    },
    documentationUrl: 'https://learn.microsoft.com/azure/storage/blobs/',
    category: 'object',
  },
  digitalocean: {
    id: 'digitalocean',
    name: 'DigitalOcean Spaces',
    shortName: 'DO Spaces',
    brandColor: '#0080FF',
    icon: '🌊',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 5 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://docs.digitalocean.com/products/spaces/',
    category: 'object',
  },
  cloudflare_r2: {
    id: 'cloudflare_r2',
    name: 'Cloudflare R2',
    shortName: 'R2',
    brandColor: '#F38020',
    icon: '🟧',
    authKind: 'apikey',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: 5 * 1024 * 1024 * 1024 * 1024,
    },
    documentationUrl: 'https://developers.cloudflare.com/r2/',
    category: 'object',
  },
  webdav: {
    id: 'webdav',
    name: 'WebDAV',
    shortName: 'WebDAV',
    brandColor: '#7E57C2',
    icon: '🟪',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://datatracker.ietf.org/doc/html/rfc4918',
    category: 'protocol',
  },
  ftp: {
    id: 'ftp',
    name: 'FTP',
    shortName: 'FTP',
    brandColor: '#A1887F',
    icon: '🟫',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://datatracker.ietf.org/doc/html/rfc959',
    category: 'protocol',
  },
  sftp: {
    id: 'sftp',
    name: 'SFTP',
    shortName: 'SFTP',
    brandColor: '#558B2F',
    icon: '🟩',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer',
    category: 'protocol',
  },
  nextcloud: {
    id: 'nextcloud',
    name: 'Nextcloud',
    shortName: 'Nextcloud',
    brandColor: '#0082C9',
    icon: '🟦',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://docs.nextcloud.com/server/latest/developer_manual/',
    category: 'selfhosted',
  },
  owncloud: {
    id: 'owncloud',
    name: 'ownCloud',
    shortName: 'ownCloud',
    brandColor: '#041E42',
    icon: '🔵',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://doc.owncloud.com/docs/next/',
    category: 'selfhosted',
  },
  seafile: {
    id: 'seafile',
    name: 'Seafile',
    shortName: 'Seafile',
    brandColor: '#FF671B',
    icon: '🟧',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://manual.seafile.com/develop/web_api/',
    category: 'selfhosted',
  },
  synology: {
    id: 'synology',
    name: 'Synology NAS',
    shortName: 'Synology',
    brandColor: '#0072C6',
    icon: '🟦',
    authKind: 'userpass',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: true,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://kb.synology.com/DSM/help/DSM/DeveloperGuide',
    category: 'selfhosted',
  },
  local: {
    id: 'local',
    name: 'Pasta local',
    shortName: 'Local',
    brandColor: '#607D8B',
    icon: '💾',
    authKind: 'connection',
    capabilities: {
      read: true,
      write: true,
      delete: true,
      mkdir: true,
      rename: true,
      quota: false,
      resumable: true,
      streaming: true,
      chunking: true,
      maxFileSize: infinite,
    },
    documentationUrl: 'https://nodejs.org/api/fs.html',
    category: 'selfhosted',
  },
};

export const ALL_PROVIDERS = Object.values(PROVIDER_REGISTRY);

export const SUPPORTED_PROVIDER_COUNT = ALL_PROVIDERS.length;
